# Generated by Django 6.1.1 on 2026-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watches/'),
        ),
    ]
