# Generated by Django 6.1.1 on 2026-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_watch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='collection',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('Premium', 'Premium'), ('Everyday', 'Everyday'), ('Minimal', 'Minimal'), ('New Arrivals', 'New Arrivals')], max_length=100),
        ),
    ]
