# Generated by Django 6.1.1 on 2026-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_watch_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='collection',
            field=models.CharField(blank=True, choices=[('Prestige', 'Prestige'), ('Heritage', 'Heritage'), ('Essential', 'Essential'), ('Form', 'Form'), ('New Edition', 'New Edition')], max_length=100),
        ),
    ]
