# Generated by Django 6.1.1 on 2026-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='case',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='strap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watch',
            name='water_resistance',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
