# Generated by Django 6.1.1 on 2026-09-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_watch_case_watch_dial_watch_movement_watch_strap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='watches/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.watch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
