# Generated by Django 6.1.1 on 2026-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_watchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='collection',
            field=models.CharField(blank=True, choices=[('Full Collection', 'Full Collection'), ('Classic', 'Classic'), ('Premium', 'Premium'), ('Everyday', 'Everyday'), ('Automatic', 'Automatic'), ('Chronograph', 'Chronograph'), ('Leather Strap', 'Leather Strap'), ('Limited Edition', 'Limited Edition')], max_length=100),
        ),
    ]
